1.User-Defined Exception in Python
